### ISSUE TITLE
Overwrite background after final reboot

### ISSUE THREAD

**Issue by mlhaigh** [fireeye/flare-vm#25] opened 2017-09-08 16:55 UTC
When running the FlareVM script on a Windows VM downloaded from Microsoft, Windows overwrites the FLARE background during the final reboot.

**Comment by iphelix** [comment] 2017-10-06 23:24
Thanks, confirmed this issue. Going to look into this.

**Comment by htnhan** [comment] 2018-04-05 00:54
@mlhaigh Can you check the latest script to see if you still have the same problem. It should be fixed with a new version of flarevm package.

**Comment by htnhan** [comment] 2018-04-10 02:03
Is it on windows 10? I have tested multiple times on 7 but can not seem to reproduce it

**Comment by htnhan** [comment] 2018-11-20 00:55
@mlhaigh We just have a new update for FLARE VM. It *should* support windows 10 properly now. After the installation, you still need to reboot to see the background gets updated sometimes. However, the issue should be fixed. Do you mind testing the installation again?

**Comment by htnhan** [comment] 2018-12-22 08:20
Close due to inactivity. FLARE VM should support windows 10 properly now.

**Closed by htnhan** 2018-12-22 08:20 UTC
Labels: bug
